// flow-typed signature: c4330d09f172e71f80ae631406dac332
// flow-typed version: <<STUB>>/easing_v^1.2.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'easing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'easing/browser-easing' {
  declare module.exports: any;
}

declare module 'easing/docs/2eaaf22e5222d429/bundle' {
  declare module.exports: any;
}

declare module 'easing/docs/882a0dbd2befeb3f/bundle' {
  declare module.exports: any;
}

declare module 'easing/docs/service-worker' {
  declare module.exports: any;
}

declare module 'easing/lib/event' {
  declare module.exports: any;
}

declare module 'easing/lib/functions' {
  declare module.exports: any;
}

declare module 'easing/lib/index' {
  declare module.exports: any;
}

declare module 'easing/lib/static' {
  declare module.exports: any;
}

declare module 'easing/lib/stream' {
  declare module.exports: any;
}

declare module 'easing/src/event' {
  declare module.exports: any;
}

declare module 'easing/src/functions' {
  declare module.exports: any;
}

declare module 'easing/src/index' {
  declare module.exports: any;
}

declare module 'easing/src/static' {
  declare module.exports: any;
}

declare module 'easing/src/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'easing/browser-easing.js' {
  declare module.exports: $Exports<'easing/browser-easing'>;
}
declare module 'easing/docs/2eaaf22e5222d429/bundle.js' {
  declare module.exports: $Exports<'easing/docs/2eaaf22e5222d429/bundle'>;
}
declare module 'easing/docs/882a0dbd2befeb3f/bundle.js' {
  declare module.exports: $Exports<'easing/docs/882a0dbd2befeb3f/bundle'>;
}
declare module 'easing/docs/service-worker.js' {
  declare module.exports: $Exports<'easing/docs/service-worker'>;
}
declare module 'easing/lib/event.js' {
  declare module.exports: $Exports<'easing/lib/event'>;
}
declare module 'easing/lib/functions.js' {
  declare module.exports: $Exports<'easing/lib/functions'>;
}
declare module 'easing/lib/index.js' {
  declare module.exports: $Exports<'easing/lib/index'>;
}
declare module 'easing/lib/static.js' {
  declare module.exports: $Exports<'easing/lib/static'>;
}
declare module 'easing/lib/stream.js' {
  declare module.exports: $Exports<'easing/lib/stream'>;
}
declare module 'easing/src/event.js' {
  declare module.exports: $Exports<'easing/src/event'>;
}
declare module 'easing/src/functions.js' {
  declare module.exports: $Exports<'easing/src/functions'>;
}
declare module 'easing/src/index.js' {
  declare module.exports: $Exports<'easing/src/index'>;
}
declare module 'easing/src/static.js' {
  declare module.exports: $Exports<'easing/src/static'>;
}
declare module 'easing/src/stream.js' {
  declare module.exports: $Exports<'easing/src/stream'>;
}
