// flow-typed signature: 34b29d6733e8c076e3577774a1646824
// flow-typed version: <<STUB>>/ionicons_v^4.5.5/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ionicons/dist/collection/icon/icon' {
  declare module.exports: any;
}

declare module 'ionicons/dist/collection/icon/svg/index.esm' {
  declare module.exports: any;
}

declare module 'ionicons/dist/collection/icon/svg/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/collection/icon/utils' {
  declare module.exports: any;
}

declare module 'ionicons/dist/collection/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/collection/interface' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/build/chunk-1ca7e569' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/build/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/build/uqr5vpdq.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/build/uqr5vpdq.sc.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/ionicons.components' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/ionicons.core' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es2017/ionicons.define' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/build/chunk-1ca7e569' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/build/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/build/uqr5vpdq.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/build/uqr5vpdq.sc.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/ionicons.components' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/ionicons.core' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/ionicons.define' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/array' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/css-shim' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/dom' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/fetch' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/map' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/object' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/promise' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/string' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/tslib' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/es5/polyfills/url' {
  declare module.exports: any;
}

declare module 'ionicons/dist/esm/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/chunk-033a0284.es5' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/chunk-1ca7e569' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/index.es5' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/ionicons.dkb1z4hj' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/ionicons.dy5iahpg' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/svg/index.esm' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/svg/index' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/uqr5vpdq.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/uqr5vpdq.es5.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/uqr5vpdq.sc.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/ionicons/uqr5vpdq.sc.es5.entry' {
  declare module.exports: any;
}

declare module 'ionicons/dist/loader/index.es2017' {
  declare module.exports: any;
}

declare module 'ionicons/dist/loader/index' {
  declare module.exports: any;
}

declare module 'ionicons/icons/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ionicons/dist/collection/icon/icon.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/icon/icon'>;
}
declare module 'ionicons/dist/collection/icon/svg/index.esm.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/icon/svg/index.esm'>;
}
declare module 'ionicons/dist/collection/icon/svg/index.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/icon/svg/index'>;
}
declare module 'ionicons/dist/collection/icon/utils.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/icon/utils'>;
}
declare module 'ionicons/dist/collection/index.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/index'>;
}
declare module 'ionicons/dist/collection/interface.js' {
  declare module.exports: $Exports<'ionicons/dist/collection/interface'>;
}
declare module 'ionicons/dist/esm/es2017/build/chunk-1ca7e569.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/build/chunk-1ca7e569'>;
}
declare module 'ionicons/dist/esm/es2017/build/index.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/build/index'>;
}
declare module 'ionicons/dist/esm/es2017/build/uqr5vpdq.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/build/uqr5vpdq.entry'>;
}
declare module 'ionicons/dist/esm/es2017/build/uqr5vpdq.sc.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/build/uqr5vpdq.sc.entry'>;
}
declare module 'ionicons/dist/esm/es2017/index.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/index'>;
}
declare module 'ionicons/dist/esm/es2017/ionicons.components.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/ionicons.components'>;
}
declare module 'ionicons/dist/esm/es2017/ionicons.core.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/ionicons.core'>;
}
declare module 'ionicons/dist/esm/es2017/ionicons.define.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es2017/ionicons.define'>;
}
declare module 'ionicons/dist/esm/es5/build/chunk-1ca7e569.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/build/chunk-1ca7e569'>;
}
declare module 'ionicons/dist/esm/es5/build/index.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/build/index'>;
}
declare module 'ionicons/dist/esm/es5/build/uqr5vpdq.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/build/uqr5vpdq.entry'>;
}
declare module 'ionicons/dist/esm/es5/build/uqr5vpdq.sc.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/build/uqr5vpdq.sc.entry'>;
}
declare module 'ionicons/dist/esm/es5/index.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/index'>;
}
declare module 'ionicons/dist/esm/es5/ionicons.components.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/ionicons.components'>;
}
declare module 'ionicons/dist/esm/es5/ionicons.core.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/ionicons.core'>;
}
declare module 'ionicons/dist/esm/es5/ionicons.define.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/ionicons.define'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/array.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/array'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/css-shim.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/css-shim'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/dom.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/dom'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/fetch.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/fetch'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/map.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/map'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/object.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/object'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/promise.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/promise'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/string.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/string'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/tslib.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/tslib'>;
}
declare module 'ionicons/dist/esm/es5/polyfills/url.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/es5/polyfills/url'>;
}
declare module 'ionicons/dist/esm/index.js' {
  declare module.exports: $Exports<'ionicons/dist/esm/index'>;
}
declare module 'ionicons/dist/index.js' {
  declare module.exports: $Exports<'ionicons/dist/index'>;
}
declare module 'ionicons/dist/ionicons.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons'>;
}
declare module 'ionicons/dist/ionicons/chunk-033a0284.es5.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/chunk-033a0284.es5'>;
}
declare module 'ionicons/dist/ionicons/chunk-1ca7e569.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/chunk-1ca7e569'>;
}
declare module 'ionicons/dist/ionicons/index.es5.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/index.es5'>;
}
declare module 'ionicons/dist/ionicons/index.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/index'>;
}
declare module 'ionicons/dist/ionicons/ionicons.dkb1z4hj.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/ionicons.dkb1z4hj'>;
}
declare module 'ionicons/dist/ionicons/ionicons.dy5iahpg.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/ionicons.dy5iahpg'>;
}
declare module 'ionicons/dist/ionicons/svg/index.esm.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/svg/index.esm'>;
}
declare module 'ionicons/dist/ionicons/svg/index.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/svg/index'>;
}
declare module 'ionicons/dist/ionicons/uqr5vpdq.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/uqr5vpdq.entry'>;
}
declare module 'ionicons/dist/ionicons/uqr5vpdq.es5.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/uqr5vpdq.es5.entry'>;
}
declare module 'ionicons/dist/ionicons/uqr5vpdq.sc.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/uqr5vpdq.sc.entry'>;
}
declare module 'ionicons/dist/ionicons/uqr5vpdq.sc.es5.entry.js' {
  declare module.exports: $Exports<'ionicons/dist/ionicons/uqr5vpdq.sc.es5.entry'>;
}
declare module 'ionicons/dist/loader/index.es2017.js' {
  declare module.exports: $Exports<'ionicons/dist/loader/index.es2017'>;
}
declare module 'ionicons/dist/loader/index.js' {
  declare module.exports: $Exports<'ionicons/dist/loader/index'>;
}
declare module 'ionicons/icons/index.js' {
  declare module.exports: $Exports<'ionicons/icons/index'>;
}
