// flow-typed signature: 2194dbcfe113443601dcd8853422060f
// flow-typed version: <<STUB>>/laravel-mix_v^4.0.15/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laravel-mix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'laravel-mix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laravel-mix/setup/webpack.config' {
  declare module.exports: any;
}

declare module 'laravel-mix/setup/webpack.mix' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Api' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Assert' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/BabelConfig' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/Entry' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/mock-entry' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/webpack-default' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/webpack-plugins' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/webpack-rules' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/builder/WebpackConfig' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Autoload' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/AutomaticComponent' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Browsersync' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Coffee' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Combine' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/ComponentFactory' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Components' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Copy' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Css' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/DisableNotifications' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/DumpWebpackConfig' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Example' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Extend' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Extract' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/JavaScript' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Less' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Notifications' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/PostCss' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Preact' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Preprocessor' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/PurifyCss' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/React' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Sass' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Stylus' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/TypeScript' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Version' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/components/Vue' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/config' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Dependencies' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Dispatcher' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/File' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/FileCollection' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/helpers' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/index' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Log' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Manifest' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Mix' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Paths' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/tasks/ConcatenateFilesTask' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/tasks/CopyFilesTask' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/tasks/Task' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/tasks/VersionFilesTask' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/BuildCallbackPlugin' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/CssPurifierPlugin' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/CustomTasksPlugin' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/ManifestPlugin' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/MixDefinitionsPlugin' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/webpackPlugins/MockEntryPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laravel-mix/setup/webpack.config.js' {
  declare module.exports: $Exports<'laravel-mix/setup/webpack.config'>;
}
declare module 'laravel-mix/setup/webpack.mix.js' {
  declare module.exports: $Exports<'laravel-mix/setup/webpack.mix'>;
}
declare module 'laravel-mix/src/Api.js' {
  declare module.exports: $Exports<'laravel-mix/src/Api'>;
}
declare module 'laravel-mix/src/Assert.js' {
  declare module.exports: $Exports<'laravel-mix/src/Assert'>;
}
declare module 'laravel-mix/src/BabelConfig.js' {
  declare module.exports: $Exports<'laravel-mix/src/BabelConfig'>;
}
declare module 'laravel-mix/src/builder/Entry.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/Entry'>;
}
declare module 'laravel-mix/src/builder/mock-entry.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/mock-entry'>;
}
declare module 'laravel-mix/src/builder/webpack-default.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/webpack-default'>;
}
declare module 'laravel-mix/src/builder/webpack-plugins.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/webpack-plugins'>;
}
declare module 'laravel-mix/src/builder/webpack-rules.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/webpack-rules'>;
}
declare module 'laravel-mix/src/builder/WebpackConfig.js' {
  declare module.exports: $Exports<'laravel-mix/src/builder/WebpackConfig'>;
}
declare module 'laravel-mix/src/components/Autoload.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Autoload'>;
}
declare module 'laravel-mix/src/components/AutomaticComponent.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/AutomaticComponent'>;
}
declare module 'laravel-mix/src/components/Browsersync.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Browsersync'>;
}
declare module 'laravel-mix/src/components/Coffee.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Coffee'>;
}
declare module 'laravel-mix/src/components/Combine.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Combine'>;
}
declare module 'laravel-mix/src/components/ComponentFactory.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/ComponentFactory'>;
}
declare module 'laravel-mix/src/components/Components.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Components'>;
}
declare module 'laravel-mix/src/components/Copy.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Copy'>;
}
declare module 'laravel-mix/src/components/Css.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Css'>;
}
declare module 'laravel-mix/src/components/DisableNotifications.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/DisableNotifications'>;
}
declare module 'laravel-mix/src/components/DumpWebpackConfig.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/DumpWebpackConfig'>;
}
declare module 'laravel-mix/src/components/Example.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Example'>;
}
declare module 'laravel-mix/src/components/Extend.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Extend'>;
}
declare module 'laravel-mix/src/components/Extract.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Extract'>;
}
declare module 'laravel-mix/src/components/JavaScript.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/JavaScript'>;
}
declare module 'laravel-mix/src/components/Less.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Less'>;
}
declare module 'laravel-mix/src/components/Notifications.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Notifications'>;
}
declare module 'laravel-mix/src/components/PostCss.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/PostCss'>;
}
declare module 'laravel-mix/src/components/Preact.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Preact'>;
}
declare module 'laravel-mix/src/components/Preprocessor.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Preprocessor'>;
}
declare module 'laravel-mix/src/components/PurifyCss.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/PurifyCss'>;
}
declare module 'laravel-mix/src/components/React.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/React'>;
}
declare module 'laravel-mix/src/components/Sass.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Sass'>;
}
declare module 'laravel-mix/src/components/Stylus.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Stylus'>;
}
declare module 'laravel-mix/src/components/TypeScript.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/TypeScript'>;
}
declare module 'laravel-mix/src/components/Version.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Version'>;
}
declare module 'laravel-mix/src/components/Vue.js' {
  declare module.exports: $Exports<'laravel-mix/src/components/Vue'>;
}
declare module 'laravel-mix/src/config.js' {
  declare module.exports: $Exports<'laravel-mix/src/config'>;
}
declare module 'laravel-mix/src/Dependencies.js' {
  declare module.exports: $Exports<'laravel-mix/src/Dependencies'>;
}
declare module 'laravel-mix/src/Dispatcher.js' {
  declare module.exports: $Exports<'laravel-mix/src/Dispatcher'>;
}
declare module 'laravel-mix/src/File.js' {
  declare module.exports: $Exports<'laravel-mix/src/File'>;
}
declare module 'laravel-mix/src/FileCollection.js' {
  declare module.exports: $Exports<'laravel-mix/src/FileCollection'>;
}
declare module 'laravel-mix/src/helpers.js' {
  declare module.exports: $Exports<'laravel-mix/src/helpers'>;
}
declare module 'laravel-mix/src/index.js' {
  declare module.exports: $Exports<'laravel-mix/src/index'>;
}
declare module 'laravel-mix/src/Log.js' {
  declare module.exports: $Exports<'laravel-mix/src/Log'>;
}
declare module 'laravel-mix/src/Manifest.js' {
  declare module.exports: $Exports<'laravel-mix/src/Manifest'>;
}
declare module 'laravel-mix/src/Mix.js' {
  declare module.exports: $Exports<'laravel-mix/src/Mix'>;
}
declare module 'laravel-mix/src/Paths.js' {
  declare module.exports: $Exports<'laravel-mix/src/Paths'>;
}
declare module 'laravel-mix/src/tasks/ConcatenateFilesTask.js' {
  declare module.exports: $Exports<'laravel-mix/src/tasks/ConcatenateFilesTask'>;
}
declare module 'laravel-mix/src/tasks/CopyFilesTask.js' {
  declare module.exports: $Exports<'laravel-mix/src/tasks/CopyFilesTask'>;
}
declare module 'laravel-mix/src/tasks/Task.js' {
  declare module.exports: $Exports<'laravel-mix/src/tasks/Task'>;
}
declare module 'laravel-mix/src/tasks/VersionFilesTask.js' {
  declare module.exports: $Exports<'laravel-mix/src/tasks/VersionFilesTask'>;
}
declare module 'laravel-mix/src/webpackPlugins/BuildCallbackPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/BuildCallbackPlugin'>;
}
declare module 'laravel-mix/src/webpackPlugins/CssPurifierPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/CssPurifierPlugin'>;
}
declare module 'laravel-mix/src/webpackPlugins/CustomTasksPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/CustomTasksPlugin'>;
}
declare module 'laravel-mix/src/webpackPlugins/ManifestPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/ManifestPlugin'>;
}
declare module 'laravel-mix/src/webpackPlugins/MixDefinitionsPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/MixDefinitionsPlugin'>;
}
declare module 'laravel-mix/src/webpackPlugins/MockEntryPlugin.js' {
  declare module.exports: $Exports<'laravel-mix/src/webpackPlugins/MockEntryPlugin'>;
}
