// flow-typed signature: fc8a07755bd82b733bd99abbc53a0a60
// flow-typed version: <<STUB>>/ramda-extension_v^0.7.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ramda-extension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ramda-extension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ramda-extension/dist/ramda-extension' {
  declare module.exports: any;
}

declare module 'ramda-extension/dist/ramda-extension.min' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysEmptyArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysEmptyObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysEmptyString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysNull-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysOne-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/alwaysZero-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/applyCompose-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/applyIfFunction-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/applyIfNotNil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/applyPipe-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/argumentsToList-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/assocDotPath-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/between-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/callIfFunction-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/camelizeKeys-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/composeC-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/constructRegExp-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/containsAll-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/containsAny-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/containsNone-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/cx-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultArgs-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToEmptyArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToEmptyObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToEmptyString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToFalse-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToOne-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToTrue-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/defaultToZero-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dispatch-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dispatchWith-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dissocDotPath-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPath-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPathEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPathNotEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPathNotSatisfies-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPathOr-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/dotPathSatisfies-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/duplicate-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/endsWithSuffix-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/endsWithSuffixIgnoreCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsLength-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsStringIgnoreCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToEmptyArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToEmptyObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToEmptyString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToFalse-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToNull-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToOne-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToTrue-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/equalsToZero-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/findNotNil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/flattenArgs-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/flattenValues-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/flipIncludes-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/gteThanLength-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/gtThanLength-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/includes-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isError-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isFalsy-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isFunction-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNegative-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNilOrEmpty-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNilOrEmptyString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotEmpty-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotNaN-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotNil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotNilObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotNumeric-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNotRegExp-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNumber-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isNumeric-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isPlainObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isPositive-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isPromise-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isRegExp-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/isTruthy-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/joinWithDash-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/joinWithDot-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/joinWithSpace-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/joinWithUnderscore-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/keyMirror-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/listToString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/log-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/lteThanLength-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/ltThanLength-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mapIndexed-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mapKeys-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mapKeysAndValues-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mapKeysWithValue-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/memoizeWithIdentity-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mergeDeepAllWith-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mergeDeepAllWithKey-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mergeDeepLeftAll-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mergeDeepRightAll-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/mergeWithDotPath-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/noop-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToEmptyArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToEmptyObject-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToEmptyString-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToFalse-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToNull-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToOne-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToTrue-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notEqualToZero-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notFlipInclude-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/notInclude-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/objOfOver-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/overHead-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/padLeft-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/padLeftUntil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/padRight-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/padRightUntil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/pathNotEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/pathNotSatisfies-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/pipeC-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/propNotEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/propNotSatisfies-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/reduceCallable-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/reduceSource-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/rejectEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/rejectNil-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/replicate-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/searchInArray-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/searchInArrayWith-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/splitByDot-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/splitByNonAlphaNumeric-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/startsWithPrefix-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/startsWithPrefixIgnoreCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toCamelCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toDotCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toggle-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toKebabCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toLowerFirst-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toPascalCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toScreamingSnakeCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toSnakeCase-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/toUpperFirst-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/trace-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/unfoldObjectDots-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/valueMirror-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/viewEq-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/viewWith-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/xPairs-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/__tests__/xPairsRight-test' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysEmptyArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysEmptyObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysNull' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysOne' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/alwaysZero' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/applyCompose' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/applyIfFunction' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/applyIfNotNil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/applyPipe' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/argumentsToList' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/assocDotPath' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/between' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/callIfFunction' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/camelizeKeys' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/composeC' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/constructRegExp' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/containsAll' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/containsAny' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/containsNone' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/cx' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaulArgs' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToEmptyArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToEmptyObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToFalse' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToOne' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToTrue' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/defaultToZero' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dispatch' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dispatchWith' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dissocDotPath' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPath' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPathEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPathNotEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPathNotSatisfies' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPathOr' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/dotPathSatisfies' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/duplicate' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/endsWithSuffix' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/endsWithSuffixIgnoreCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsLength' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsStringIgnoreCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToEmptyArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToEmptyObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToFalse' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToNull' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToOne' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToTrue' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsToZero' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/equalsZero' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/findNotNil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/flattenArgs' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/flattenValues' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/flipIncludes' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/gteThanLength' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/gtThanLength' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/headArg' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/includes' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/index' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/internal/alwaysNew' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/internal/lengthUtils' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/internal/nonAlphaNumericRegExp' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/internal/primitives' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isError' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isFalsy' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isFunction' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNegative' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNilOrEmpty' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNilOrEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotEmpty' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotNaN' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotNil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotNilObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotNumeric' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNotRegExp' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNumber' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isNumeric' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isPlainObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isPositive' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isPromise' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isRegExp' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/isTruthy' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/joinWithDash' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/joinWithDot' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/joinWithSpace' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/joinWithUnderscore' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/keyMirror' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/lastArg' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/listToString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/log' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/lteThanLength' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/ltThanLength' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mapIndexed' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mapKeys' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mapKeysAndValues' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mapKeysWithValue' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/memoizeWithIdentity' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mergeDeepAllWith' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mergeDeepAllWithKey' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mergeDeepLeftAll' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mergeDeepRightAll' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/mergeWithDotPath' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/noop' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEmpty' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqual' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToEmptyArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToEmptyObject' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToEmptyString' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToFalse' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToNull' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToOne' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToTrue' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notEqualToZero' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notFlipInclude' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notInclude' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notNaN' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notNil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/notNumeric' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/objOfOver' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/overHead' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/padLeft' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/padLeftUntil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/padRight' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/padRightUntil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/pathNotEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/pathNotSatisfies' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/pipeC' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/propNotEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/propNotSatisfies' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/ramda-extension' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/reduceCallable' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/reduceSource' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/rejectEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/rejectNil' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/replicate' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/searchInArray' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/searchInArrayWith' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/splitByDot' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/splitByNonAlphaNumeric' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/startsWithPrefix' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/startsWithPrefixIgnoreCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/testUtils' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toCamelCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toDotCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toggle' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toKebabCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toLowerFirst' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toPascalCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toScreamingSnakeCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toSnakeCase' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/toUpperFirst' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/trace' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/unfoldObjectDots' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/valueMirror' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/viewEq' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/viewWith' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/xPairs' {
  declare module.exports: any;
}

declare module 'ramda-extension/es/xPairsRight' {
  declare module.exports: any;
}

declare module 'ramda-extension/lib/ramda-extension' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ramda-extension/dist/ramda-extension.js' {
  declare module.exports: $Exports<'ramda-extension/dist/ramda-extension'>;
}
declare module 'ramda-extension/dist/ramda-extension.min.js' {
  declare module.exports: $Exports<'ramda-extension/dist/ramda-extension.min'>;
}
declare module 'ramda-extension/es/__tests__/alwaysEmptyArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysEmptyArray-test'>;
}
declare module 'ramda-extension/es/__tests__/alwaysEmptyObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysEmptyObject-test'>;
}
declare module 'ramda-extension/es/__tests__/alwaysEmptyString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysEmptyString-test'>;
}
declare module 'ramda-extension/es/__tests__/alwaysNull-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysNull-test'>;
}
declare module 'ramda-extension/es/__tests__/alwaysOne-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysOne-test'>;
}
declare module 'ramda-extension/es/__tests__/alwaysZero-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/alwaysZero-test'>;
}
declare module 'ramda-extension/es/__tests__/applyCompose-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/applyCompose-test'>;
}
declare module 'ramda-extension/es/__tests__/applyIfFunction-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/applyIfFunction-test'>;
}
declare module 'ramda-extension/es/__tests__/applyIfNotNil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/applyIfNotNil-test'>;
}
declare module 'ramda-extension/es/__tests__/applyPipe-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/applyPipe-test'>;
}
declare module 'ramda-extension/es/__tests__/argumentsToList-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/argumentsToList-test'>;
}
declare module 'ramda-extension/es/__tests__/assocDotPath-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/assocDotPath-test'>;
}
declare module 'ramda-extension/es/__tests__/between-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/between-test'>;
}
declare module 'ramda-extension/es/__tests__/callIfFunction-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/callIfFunction-test'>;
}
declare module 'ramda-extension/es/__tests__/camelizeKeys-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/camelizeKeys-test'>;
}
declare module 'ramda-extension/es/__tests__/composeC-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/composeC-test'>;
}
declare module 'ramda-extension/es/__tests__/constructRegExp-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/constructRegExp-test'>;
}
declare module 'ramda-extension/es/__tests__/containsAll-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/containsAll-test'>;
}
declare module 'ramda-extension/es/__tests__/containsAny-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/containsAny-test'>;
}
declare module 'ramda-extension/es/__tests__/containsNone-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/containsNone-test'>;
}
declare module 'ramda-extension/es/__tests__/cx-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/cx-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultArgs-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultArgs-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToEmptyArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToEmptyArray-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToEmptyObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToEmptyObject-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToEmptyString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToEmptyString-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToFalse-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToFalse-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToOne-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToOne-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToTrue-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToTrue-test'>;
}
declare module 'ramda-extension/es/__tests__/defaultToZero-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/defaultToZero-test'>;
}
declare module 'ramda-extension/es/__tests__/dispatch-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dispatch-test'>;
}
declare module 'ramda-extension/es/__tests__/dispatchWith-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dispatchWith-test'>;
}
declare module 'ramda-extension/es/__tests__/dissocDotPath-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dissocDotPath-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPath-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPath-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPathEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPathEq-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPathNotEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPathNotEq-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPathNotSatisfies-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPathNotSatisfies-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPathOr-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPathOr-test'>;
}
declare module 'ramda-extension/es/__tests__/dotPathSatisfies-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/dotPathSatisfies-test'>;
}
declare module 'ramda-extension/es/__tests__/duplicate-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/duplicate-test'>;
}
declare module 'ramda-extension/es/__tests__/endsWithSuffix-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/endsWithSuffix-test'>;
}
declare module 'ramda-extension/es/__tests__/endsWithSuffixIgnoreCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/endsWithSuffixIgnoreCase-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsLength-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsLength-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsStringIgnoreCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsStringIgnoreCase-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToEmptyArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToEmptyArray-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToEmptyObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToEmptyObject-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToEmptyString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToEmptyString-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToFalse-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToFalse-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToNull-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToNull-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToOne-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToOne-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToTrue-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToTrue-test'>;
}
declare module 'ramda-extension/es/__tests__/equalsToZero-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/equalsToZero-test'>;
}
declare module 'ramda-extension/es/__tests__/findNotNil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/findNotNil-test'>;
}
declare module 'ramda-extension/es/__tests__/flattenArgs-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/flattenArgs-test'>;
}
declare module 'ramda-extension/es/__tests__/flattenValues-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/flattenValues-test'>;
}
declare module 'ramda-extension/es/__tests__/flipIncludes-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/flipIncludes-test'>;
}
declare module 'ramda-extension/es/__tests__/gteThanLength-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/gteThanLength-test'>;
}
declare module 'ramda-extension/es/__tests__/gtThanLength-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/gtThanLength-test'>;
}
declare module 'ramda-extension/es/__tests__/includes-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/includes-test'>;
}
declare module 'ramda-extension/es/__tests__/isArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isArray-test'>;
}
declare module 'ramda-extension/es/__tests__/isError-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isError-test'>;
}
declare module 'ramda-extension/es/__tests__/isFalsy-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isFalsy-test'>;
}
declare module 'ramda-extension/es/__tests__/isFunction-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isFunction-test'>;
}
declare module 'ramda-extension/es/__tests__/isNegative-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNegative-test'>;
}
declare module 'ramda-extension/es/__tests__/isNilOrEmpty-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNilOrEmpty-test'>;
}
declare module 'ramda-extension/es/__tests__/isNilOrEmptyString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNilOrEmptyString-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotEmpty-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotEmpty-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotNaN-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotNaN-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotNil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotNil-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotNilObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotNilObject-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotNumeric-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotNumeric-test'>;
}
declare module 'ramda-extension/es/__tests__/isNotRegExp-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNotRegExp-test'>;
}
declare module 'ramda-extension/es/__tests__/isNumber-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNumber-test'>;
}
declare module 'ramda-extension/es/__tests__/isNumeric-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isNumeric-test'>;
}
declare module 'ramda-extension/es/__tests__/isObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isObject-test'>;
}
declare module 'ramda-extension/es/__tests__/isPlainObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isPlainObject-test'>;
}
declare module 'ramda-extension/es/__tests__/isPositive-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isPositive-test'>;
}
declare module 'ramda-extension/es/__tests__/isPromise-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isPromise-test'>;
}
declare module 'ramda-extension/es/__tests__/isRegExp-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isRegExp-test'>;
}
declare module 'ramda-extension/es/__tests__/isString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isString-test'>;
}
declare module 'ramda-extension/es/__tests__/isTruthy-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/isTruthy-test'>;
}
declare module 'ramda-extension/es/__tests__/joinWithDash-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/joinWithDash-test'>;
}
declare module 'ramda-extension/es/__tests__/joinWithDot-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/joinWithDot-test'>;
}
declare module 'ramda-extension/es/__tests__/joinWithSpace-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/joinWithSpace-test'>;
}
declare module 'ramda-extension/es/__tests__/joinWithUnderscore-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/joinWithUnderscore-test'>;
}
declare module 'ramda-extension/es/__tests__/keyMirror-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/keyMirror-test'>;
}
declare module 'ramda-extension/es/__tests__/listToString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/listToString-test'>;
}
declare module 'ramda-extension/es/__tests__/log-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/log-test'>;
}
declare module 'ramda-extension/es/__tests__/lteThanLength-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/lteThanLength-test'>;
}
declare module 'ramda-extension/es/__tests__/ltThanLength-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/ltThanLength-test'>;
}
declare module 'ramda-extension/es/__tests__/mapIndexed-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mapIndexed-test'>;
}
declare module 'ramda-extension/es/__tests__/mapKeys-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mapKeys-test'>;
}
declare module 'ramda-extension/es/__tests__/mapKeysAndValues-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mapKeysAndValues-test'>;
}
declare module 'ramda-extension/es/__tests__/mapKeysWithValue-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mapKeysWithValue-test'>;
}
declare module 'ramda-extension/es/__tests__/memoizeWithIdentity-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/memoizeWithIdentity-test'>;
}
declare module 'ramda-extension/es/__tests__/mergeDeepAllWith-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mergeDeepAllWith-test'>;
}
declare module 'ramda-extension/es/__tests__/mergeDeepAllWithKey-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mergeDeepAllWithKey-test'>;
}
declare module 'ramda-extension/es/__tests__/mergeDeepLeftAll-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mergeDeepLeftAll-test'>;
}
declare module 'ramda-extension/es/__tests__/mergeDeepRightAll-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mergeDeepRightAll-test'>;
}
declare module 'ramda-extension/es/__tests__/mergeWithDotPath-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/mergeWithDotPath-test'>;
}
declare module 'ramda-extension/es/__tests__/noop-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/noop-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToEmptyArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToEmptyArray-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToEmptyObject-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToEmptyObject-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToEmptyString-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToEmptyString-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToFalse-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToFalse-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToNull-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToNull-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToOne-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToOne-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToTrue-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToTrue-test'>;
}
declare module 'ramda-extension/es/__tests__/notEqualToZero-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notEqualToZero-test'>;
}
declare module 'ramda-extension/es/__tests__/notFlipInclude-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notFlipInclude-test'>;
}
declare module 'ramda-extension/es/__tests__/notInclude-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/notInclude-test'>;
}
declare module 'ramda-extension/es/__tests__/objOfOver-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/objOfOver-test'>;
}
declare module 'ramda-extension/es/__tests__/overHead-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/overHead-test'>;
}
declare module 'ramda-extension/es/__tests__/padLeft-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/padLeft-test'>;
}
declare module 'ramda-extension/es/__tests__/padLeftUntil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/padLeftUntil-test'>;
}
declare module 'ramda-extension/es/__tests__/padRight-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/padRight-test'>;
}
declare module 'ramda-extension/es/__tests__/padRightUntil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/padRightUntil-test'>;
}
declare module 'ramda-extension/es/__tests__/pathNotEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/pathNotEq-test'>;
}
declare module 'ramda-extension/es/__tests__/pathNotSatisfies-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/pathNotSatisfies-test'>;
}
declare module 'ramda-extension/es/__tests__/pipeC-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/pipeC-test'>;
}
declare module 'ramda-extension/es/__tests__/propNotEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/propNotEq-test'>;
}
declare module 'ramda-extension/es/__tests__/propNotSatisfies-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/propNotSatisfies-test'>;
}
declare module 'ramda-extension/es/__tests__/reduceCallable-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/reduceCallable-test'>;
}
declare module 'ramda-extension/es/__tests__/reduceSource-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/reduceSource-test'>;
}
declare module 'ramda-extension/es/__tests__/rejectEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/rejectEq-test'>;
}
declare module 'ramda-extension/es/__tests__/rejectNil-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/rejectNil-test'>;
}
declare module 'ramda-extension/es/__tests__/replicate-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/replicate-test'>;
}
declare module 'ramda-extension/es/__tests__/searchInArray-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/searchInArray-test'>;
}
declare module 'ramda-extension/es/__tests__/searchInArrayWith-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/searchInArrayWith-test'>;
}
declare module 'ramda-extension/es/__tests__/splitByDot-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/splitByDot-test'>;
}
declare module 'ramda-extension/es/__tests__/splitByNonAlphaNumeric-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/splitByNonAlphaNumeric-test'>;
}
declare module 'ramda-extension/es/__tests__/startsWithPrefix-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/startsWithPrefix-test'>;
}
declare module 'ramda-extension/es/__tests__/startsWithPrefixIgnoreCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/startsWithPrefixIgnoreCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toCamelCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toCamelCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toDotCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toDotCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toggle-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toggle-test'>;
}
declare module 'ramda-extension/es/__tests__/toKebabCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toKebabCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toLowerFirst-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toLowerFirst-test'>;
}
declare module 'ramda-extension/es/__tests__/toPascalCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toPascalCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toScreamingSnakeCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toScreamingSnakeCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toSnakeCase-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toSnakeCase-test'>;
}
declare module 'ramda-extension/es/__tests__/toUpperFirst-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/toUpperFirst-test'>;
}
declare module 'ramda-extension/es/__tests__/trace-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/trace-test'>;
}
declare module 'ramda-extension/es/__tests__/unfoldObjectDots-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/unfoldObjectDots-test'>;
}
declare module 'ramda-extension/es/__tests__/valueMirror-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/valueMirror-test'>;
}
declare module 'ramda-extension/es/__tests__/viewEq-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/viewEq-test'>;
}
declare module 'ramda-extension/es/__tests__/viewWith-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/viewWith-test'>;
}
declare module 'ramda-extension/es/__tests__/xPairs-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/xPairs-test'>;
}
declare module 'ramda-extension/es/__tests__/xPairsRight-test.js' {
  declare module.exports: $Exports<'ramda-extension/es/__tests__/xPairsRight-test'>;
}
declare module 'ramda-extension/es/alwaysEmptyArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysEmptyArray'>;
}
declare module 'ramda-extension/es/alwaysEmptyObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysEmptyObject'>;
}
declare module 'ramda-extension/es/alwaysEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysEmptyString'>;
}
declare module 'ramda-extension/es/alwaysNull.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysNull'>;
}
declare module 'ramda-extension/es/alwaysOne.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysOne'>;
}
declare module 'ramda-extension/es/alwaysZero.js' {
  declare module.exports: $Exports<'ramda-extension/es/alwaysZero'>;
}
declare module 'ramda-extension/es/applyCompose.js' {
  declare module.exports: $Exports<'ramda-extension/es/applyCompose'>;
}
declare module 'ramda-extension/es/applyIfFunction.js' {
  declare module.exports: $Exports<'ramda-extension/es/applyIfFunction'>;
}
declare module 'ramda-extension/es/applyIfNotNil.js' {
  declare module.exports: $Exports<'ramda-extension/es/applyIfNotNil'>;
}
declare module 'ramda-extension/es/applyPipe.js' {
  declare module.exports: $Exports<'ramda-extension/es/applyPipe'>;
}
declare module 'ramda-extension/es/argumentsToList.js' {
  declare module.exports: $Exports<'ramda-extension/es/argumentsToList'>;
}
declare module 'ramda-extension/es/assocDotPath.js' {
  declare module.exports: $Exports<'ramda-extension/es/assocDotPath'>;
}
declare module 'ramda-extension/es/between.js' {
  declare module.exports: $Exports<'ramda-extension/es/between'>;
}
declare module 'ramda-extension/es/callIfFunction.js' {
  declare module.exports: $Exports<'ramda-extension/es/callIfFunction'>;
}
declare module 'ramda-extension/es/camelizeKeys.js' {
  declare module.exports: $Exports<'ramda-extension/es/camelizeKeys'>;
}
declare module 'ramda-extension/es/composeC.js' {
  declare module.exports: $Exports<'ramda-extension/es/composeC'>;
}
declare module 'ramda-extension/es/constructRegExp.js' {
  declare module.exports: $Exports<'ramda-extension/es/constructRegExp'>;
}
declare module 'ramda-extension/es/containsAll.js' {
  declare module.exports: $Exports<'ramda-extension/es/containsAll'>;
}
declare module 'ramda-extension/es/containsAny.js' {
  declare module.exports: $Exports<'ramda-extension/es/containsAny'>;
}
declare module 'ramda-extension/es/containsNone.js' {
  declare module.exports: $Exports<'ramda-extension/es/containsNone'>;
}
declare module 'ramda-extension/es/cx.js' {
  declare module.exports: $Exports<'ramda-extension/es/cx'>;
}
declare module 'ramda-extension/es/defaulArgs.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaulArgs'>;
}
declare module 'ramda-extension/es/defaultToEmptyArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToEmptyArray'>;
}
declare module 'ramda-extension/es/defaultToEmptyObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToEmptyObject'>;
}
declare module 'ramda-extension/es/defaultToEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToEmptyString'>;
}
declare module 'ramda-extension/es/defaultToFalse.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToFalse'>;
}
declare module 'ramda-extension/es/defaultToOne.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToOne'>;
}
declare module 'ramda-extension/es/defaultToTrue.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToTrue'>;
}
declare module 'ramda-extension/es/defaultToZero.js' {
  declare module.exports: $Exports<'ramda-extension/es/defaultToZero'>;
}
declare module 'ramda-extension/es/dispatch.js' {
  declare module.exports: $Exports<'ramda-extension/es/dispatch'>;
}
declare module 'ramda-extension/es/dispatchWith.js' {
  declare module.exports: $Exports<'ramda-extension/es/dispatchWith'>;
}
declare module 'ramda-extension/es/dissocDotPath.js' {
  declare module.exports: $Exports<'ramda-extension/es/dissocDotPath'>;
}
declare module 'ramda-extension/es/dotPath.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPath'>;
}
declare module 'ramda-extension/es/dotPathEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPathEq'>;
}
declare module 'ramda-extension/es/dotPathNotEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPathNotEq'>;
}
declare module 'ramda-extension/es/dotPathNotSatisfies.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPathNotSatisfies'>;
}
declare module 'ramda-extension/es/dotPathOr.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPathOr'>;
}
declare module 'ramda-extension/es/dotPathSatisfies.js' {
  declare module.exports: $Exports<'ramda-extension/es/dotPathSatisfies'>;
}
declare module 'ramda-extension/es/duplicate.js' {
  declare module.exports: $Exports<'ramda-extension/es/duplicate'>;
}
declare module 'ramda-extension/es/endsWithSuffix.js' {
  declare module.exports: $Exports<'ramda-extension/es/endsWithSuffix'>;
}
declare module 'ramda-extension/es/endsWithSuffixIgnoreCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/endsWithSuffixIgnoreCase'>;
}
declare module 'ramda-extension/es/equalsEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsEmptyString'>;
}
declare module 'ramda-extension/es/equalsLength.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsLength'>;
}
declare module 'ramda-extension/es/equalsStringIgnoreCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsStringIgnoreCase'>;
}
declare module 'ramda-extension/es/equalsToEmptyArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToEmptyArray'>;
}
declare module 'ramda-extension/es/equalsToEmptyObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToEmptyObject'>;
}
declare module 'ramda-extension/es/equalsToEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToEmptyString'>;
}
declare module 'ramda-extension/es/equalsToFalse.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToFalse'>;
}
declare module 'ramda-extension/es/equalsToNull.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToNull'>;
}
declare module 'ramda-extension/es/equalsToOne.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToOne'>;
}
declare module 'ramda-extension/es/equalsToTrue.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToTrue'>;
}
declare module 'ramda-extension/es/equalsToZero.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsToZero'>;
}
declare module 'ramda-extension/es/equalsZero.js' {
  declare module.exports: $Exports<'ramda-extension/es/equalsZero'>;
}
declare module 'ramda-extension/es/findNotNil.js' {
  declare module.exports: $Exports<'ramda-extension/es/findNotNil'>;
}
declare module 'ramda-extension/es/flattenArgs.js' {
  declare module.exports: $Exports<'ramda-extension/es/flattenArgs'>;
}
declare module 'ramda-extension/es/flattenValues.js' {
  declare module.exports: $Exports<'ramda-extension/es/flattenValues'>;
}
declare module 'ramda-extension/es/flipIncludes.js' {
  declare module.exports: $Exports<'ramda-extension/es/flipIncludes'>;
}
declare module 'ramda-extension/es/gteThanLength.js' {
  declare module.exports: $Exports<'ramda-extension/es/gteThanLength'>;
}
declare module 'ramda-extension/es/gtThanLength.js' {
  declare module.exports: $Exports<'ramda-extension/es/gtThanLength'>;
}
declare module 'ramda-extension/es/headArg.js' {
  declare module.exports: $Exports<'ramda-extension/es/headArg'>;
}
declare module 'ramda-extension/es/includes.js' {
  declare module.exports: $Exports<'ramda-extension/es/includes'>;
}
declare module 'ramda-extension/es/index.js' {
  declare module.exports: $Exports<'ramda-extension/es/index'>;
}
declare module 'ramda-extension/es/internal/alwaysNew.js' {
  declare module.exports: $Exports<'ramda-extension/es/internal/alwaysNew'>;
}
declare module 'ramda-extension/es/internal/lengthUtils.js' {
  declare module.exports: $Exports<'ramda-extension/es/internal/lengthUtils'>;
}
declare module 'ramda-extension/es/internal/nonAlphaNumericRegExp.js' {
  declare module.exports: $Exports<'ramda-extension/es/internal/nonAlphaNumericRegExp'>;
}
declare module 'ramda-extension/es/internal/primitives.js' {
  declare module.exports: $Exports<'ramda-extension/es/internal/primitives'>;
}
declare module 'ramda-extension/es/isArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/isArray'>;
}
declare module 'ramda-extension/es/isError.js' {
  declare module.exports: $Exports<'ramda-extension/es/isError'>;
}
declare module 'ramda-extension/es/isFalsy.js' {
  declare module.exports: $Exports<'ramda-extension/es/isFalsy'>;
}
declare module 'ramda-extension/es/isFunction.js' {
  declare module.exports: $Exports<'ramda-extension/es/isFunction'>;
}
declare module 'ramda-extension/es/isNegative.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNegative'>;
}
declare module 'ramda-extension/es/isNilOrEmpty.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNilOrEmpty'>;
}
declare module 'ramda-extension/es/isNilOrEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNilOrEmptyString'>;
}
declare module 'ramda-extension/es/isNotEmpty.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotEmpty'>;
}
declare module 'ramda-extension/es/isNotNaN.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotNaN'>;
}
declare module 'ramda-extension/es/isNotNil.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotNil'>;
}
declare module 'ramda-extension/es/isNotNilObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotNilObject'>;
}
declare module 'ramda-extension/es/isNotNumeric.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotNumeric'>;
}
declare module 'ramda-extension/es/isNotRegExp.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNotRegExp'>;
}
declare module 'ramda-extension/es/isNumber.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNumber'>;
}
declare module 'ramda-extension/es/isNumeric.js' {
  declare module.exports: $Exports<'ramda-extension/es/isNumeric'>;
}
declare module 'ramda-extension/es/isObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/isObject'>;
}
declare module 'ramda-extension/es/isPlainObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/isPlainObject'>;
}
declare module 'ramda-extension/es/isPositive.js' {
  declare module.exports: $Exports<'ramda-extension/es/isPositive'>;
}
declare module 'ramda-extension/es/isPromise.js' {
  declare module.exports: $Exports<'ramda-extension/es/isPromise'>;
}
declare module 'ramda-extension/es/isRegExp.js' {
  declare module.exports: $Exports<'ramda-extension/es/isRegExp'>;
}
declare module 'ramda-extension/es/isString.js' {
  declare module.exports: $Exports<'ramda-extension/es/isString'>;
}
declare module 'ramda-extension/es/isTruthy.js' {
  declare module.exports: $Exports<'ramda-extension/es/isTruthy'>;
}
declare module 'ramda-extension/es/joinWithDash.js' {
  declare module.exports: $Exports<'ramda-extension/es/joinWithDash'>;
}
declare module 'ramda-extension/es/joinWithDot.js' {
  declare module.exports: $Exports<'ramda-extension/es/joinWithDot'>;
}
declare module 'ramda-extension/es/joinWithSpace.js' {
  declare module.exports: $Exports<'ramda-extension/es/joinWithSpace'>;
}
declare module 'ramda-extension/es/joinWithUnderscore.js' {
  declare module.exports: $Exports<'ramda-extension/es/joinWithUnderscore'>;
}
declare module 'ramda-extension/es/keyMirror.js' {
  declare module.exports: $Exports<'ramda-extension/es/keyMirror'>;
}
declare module 'ramda-extension/es/lastArg.js' {
  declare module.exports: $Exports<'ramda-extension/es/lastArg'>;
}
declare module 'ramda-extension/es/listToString.js' {
  declare module.exports: $Exports<'ramda-extension/es/listToString'>;
}
declare module 'ramda-extension/es/log.js' {
  declare module.exports: $Exports<'ramda-extension/es/log'>;
}
declare module 'ramda-extension/es/lteThanLength.js' {
  declare module.exports: $Exports<'ramda-extension/es/lteThanLength'>;
}
declare module 'ramda-extension/es/ltThanLength.js' {
  declare module.exports: $Exports<'ramda-extension/es/ltThanLength'>;
}
declare module 'ramda-extension/es/mapIndexed.js' {
  declare module.exports: $Exports<'ramda-extension/es/mapIndexed'>;
}
declare module 'ramda-extension/es/mapKeys.js' {
  declare module.exports: $Exports<'ramda-extension/es/mapKeys'>;
}
declare module 'ramda-extension/es/mapKeysAndValues.js' {
  declare module.exports: $Exports<'ramda-extension/es/mapKeysAndValues'>;
}
declare module 'ramda-extension/es/mapKeysWithValue.js' {
  declare module.exports: $Exports<'ramda-extension/es/mapKeysWithValue'>;
}
declare module 'ramda-extension/es/memoizeWithIdentity.js' {
  declare module.exports: $Exports<'ramda-extension/es/memoizeWithIdentity'>;
}
declare module 'ramda-extension/es/mergeDeepAllWith.js' {
  declare module.exports: $Exports<'ramda-extension/es/mergeDeepAllWith'>;
}
declare module 'ramda-extension/es/mergeDeepAllWithKey.js' {
  declare module.exports: $Exports<'ramda-extension/es/mergeDeepAllWithKey'>;
}
declare module 'ramda-extension/es/mergeDeepLeftAll.js' {
  declare module.exports: $Exports<'ramda-extension/es/mergeDeepLeftAll'>;
}
declare module 'ramda-extension/es/mergeDeepRightAll.js' {
  declare module.exports: $Exports<'ramda-extension/es/mergeDeepRightAll'>;
}
declare module 'ramda-extension/es/mergeWithDotPath.js' {
  declare module.exports: $Exports<'ramda-extension/es/mergeWithDotPath'>;
}
declare module 'ramda-extension/es/noop.js' {
  declare module.exports: $Exports<'ramda-extension/es/noop'>;
}
declare module 'ramda-extension/es/notEmpty.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEmpty'>;
}
declare module 'ramda-extension/es/notEqual.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqual'>;
}
declare module 'ramda-extension/es/notEqualToEmptyArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToEmptyArray'>;
}
declare module 'ramda-extension/es/notEqualToEmptyObject.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToEmptyObject'>;
}
declare module 'ramda-extension/es/notEqualToEmptyString.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToEmptyString'>;
}
declare module 'ramda-extension/es/notEqualToFalse.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToFalse'>;
}
declare module 'ramda-extension/es/notEqualToNull.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToNull'>;
}
declare module 'ramda-extension/es/notEqualToOne.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToOne'>;
}
declare module 'ramda-extension/es/notEqualToTrue.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToTrue'>;
}
declare module 'ramda-extension/es/notEqualToZero.js' {
  declare module.exports: $Exports<'ramda-extension/es/notEqualToZero'>;
}
declare module 'ramda-extension/es/notFlipInclude.js' {
  declare module.exports: $Exports<'ramda-extension/es/notFlipInclude'>;
}
declare module 'ramda-extension/es/notInclude.js' {
  declare module.exports: $Exports<'ramda-extension/es/notInclude'>;
}
declare module 'ramda-extension/es/notNaN.js' {
  declare module.exports: $Exports<'ramda-extension/es/notNaN'>;
}
declare module 'ramda-extension/es/notNil.js' {
  declare module.exports: $Exports<'ramda-extension/es/notNil'>;
}
declare module 'ramda-extension/es/notNumeric.js' {
  declare module.exports: $Exports<'ramda-extension/es/notNumeric'>;
}
declare module 'ramda-extension/es/objOfOver.js' {
  declare module.exports: $Exports<'ramda-extension/es/objOfOver'>;
}
declare module 'ramda-extension/es/overHead.js' {
  declare module.exports: $Exports<'ramda-extension/es/overHead'>;
}
declare module 'ramda-extension/es/padLeft.js' {
  declare module.exports: $Exports<'ramda-extension/es/padLeft'>;
}
declare module 'ramda-extension/es/padLeftUntil.js' {
  declare module.exports: $Exports<'ramda-extension/es/padLeftUntil'>;
}
declare module 'ramda-extension/es/padRight.js' {
  declare module.exports: $Exports<'ramda-extension/es/padRight'>;
}
declare module 'ramda-extension/es/padRightUntil.js' {
  declare module.exports: $Exports<'ramda-extension/es/padRightUntil'>;
}
declare module 'ramda-extension/es/pathNotEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/pathNotEq'>;
}
declare module 'ramda-extension/es/pathNotSatisfies.js' {
  declare module.exports: $Exports<'ramda-extension/es/pathNotSatisfies'>;
}
declare module 'ramda-extension/es/pipeC.js' {
  declare module.exports: $Exports<'ramda-extension/es/pipeC'>;
}
declare module 'ramda-extension/es/propNotEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/propNotEq'>;
}
declare module 'ramda-extension/es/propNotSatisfies.js' {
  declare module.exports: $Exports<'ramda-extension/es/propNotSatisfies'>;
}
declare module 'ramda-extension/es/ramda-extension.js' {
  declare module.exports: $Exports<'ramda-extension/es/ramda-extension'>;
}
declare module 'ramda-extension/es/reduceCallable.js' {
  declare module.exports: $Exports<'ramda-extension/es/reduceCallable'>;
}
declare module 'ramda-extension/es/reduceSource.js' {
  declare module.exports: $Exports<'ramda-extension/es/reduceSource'>;
}
declare module 'ramda-extension/es/rejectEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/rejectEq'>;
}
declare module 'ramda-extension/es/rejectNil.js' {
  declare module.exports: $Exports<'ramda-extension/es/rejectNil'>;
}
declare module 'ramda-extension/es/replicate.js' {
  declare module.exports: $Exports<'ramda-extension/es/replicate'>;
}
declare module 'ramda-extension/es/searchInArray.js' {
  declare module.exports: $Exports<'ramda-extension/es/searchInArray'>;
}
declare module 'ramda-extension/es/searchInArrayWith.js' {
  declare module.exports: $Exports<'ramda-extension/es/searchInArrayWith'>;
}
declare module 'ramda-extension/es/splitByDot.js' {
  declare module.exports: $Exports<'ramda-extension/es/splitByDot'>;
}
declare module 'ramda-extension/es/splitByNonAlphaNumeric.js' {
  declare module.exports: $Exports<'ramda-extension/es/splitByNonAlphaNumeric'>;
}
declare module 'ramda-extension/es/startsWithPrefix.js' {
  declare module.exports: $Exports<'ramda-extension/es/startsWithPrefix'>;
}
declare module 'ramda-extension/es/startsWithPrefixIgnoreCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/startsWithPrefixIgnoreCase'>;
}
declare module 'ramda-extension/es/testUtils.js' {
  declare module.exports: $Exports<'ramda-extension/es/testUtils'>;
}
declare module 'ramda-extension/es/toCamelCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toCamelCase'>;
}
declare module 'ramda-extension/es/toDotCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toDotCase'>;
}
declare module 'ramda-extension/es/toggle.js' {
  declare module.exports: $Exports<'ramda-extension/es/toggle'>;
}
declare module 'ramda-extension/es/toKebabCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toKebabCase'>;
}
declare module 'ramda-extension/es/toLowerFirst.js' {
  declare module.exports: $Exports<'ramda-extension/es/toLowerFirst'>;
}
declare module 'ramda-extension/es/toPascalCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toPascalCase'>;
}
declare module 'ramda-extension/es/toScreamingSnakeCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toScreamingSnakeCase'>;
}
declare module 'ramda-extension/es/toSnakeCase.js' {
  declare module.exports: $Exports<'ramda-extension/es/toSnakeCase'>;
}
declare module 'ramda-extension/es/toUpperFirst.js' {
  declare module.exports: $Exports<'ramda-extension/es/toUpperFirst'>;
}
declare module 'ramda-extension/es/trace.js' {
  declare module.exports: $Exports<'ramda-extension/es/trace'>;
}
declare module 'ramda-extension/es/unfoldObjectDots.js' {
  declare module.exports: $Exports<'ramda-extension/es/unfoldObjectDots'>;
}
declare module 'ramda-extension/es/valueMirror.js' {
  declare module.exports: $Exports<'ramda-extension/es/valueMirror'>;
}
declare module 'ramda-extension/es/viewEq.js' {
  declare module.exports: $Exports<'ramda-extension/es/viewEq'>;
}
declare module 'ramda-extension/es/viewWith.js' {
  declare module.exports: $Exports<'ramda-extension/es/viewWith'>;
}
declare module 'ramda-extension/es/xPairs.js' {
  declare module.exports: $Exports<'ramda-extension/es/xPairs'>;
}
declare module 'ramda-extension/es/xPairsRight.js' {
  declare module.exports: $Exports<'ramda-extension/es/xPairsRight'>;
}
declare module 'ramda-extension/lib/ramda-extension.js' {
  declare module.exports: $Exports<'ramda-extension/lib/ramda-extension'>;
}
