// flow-typed signature: e3f290f5f9cf94695db99dece138b700
// flow-typed version: <<STUB>>/react-image-lightbox_v^5.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-lightbox/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-image-lightbox/dist/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-lightbox/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-image-lightbox/dist/index.cjs'>;
}
declare module 'react-image-lightbox/dist/index.es.js' {
  declare module.exports: $Exports<'react-image-lightbox/dist/index.es'>;
}
