// flow-typed signature: 9f0e0b19443e4a9b6b565180b8157dc8
// flow-typed version: <<STUB>>/react-notification-alert_v0.0.9/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notification-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notification-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notification-alert/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notification-alert/dist/index.js' {
  declare module.exports: $Exports<'react-notification-alert/dist/index'>;
}
declare module 'react-notification-alert/index' {
  declare module.exports: $Exports<'react-notification-alert'>;
}
declare module 'react-notification-alert/index.js' {
  declare module.exports: $Exports<'react-notification-alert'>;
}
