// flow-typed signature: ebf0e3262a5d5c7b77cebc65ca1bd320
// flow-typed version: <<STUB>>/responsive-loader_v^1.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'responsive-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'responsive-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'responsive-loader/jimp' {
  declare module.exports: any;
}

declare module 'responsive-loader/lib/adapters/jimp' {
  declare module.exports: any;
}

declare module 'responsive-loader/lib/adapters/sharp' {
  declare module.exports: any;
}

declare module 'responsive-loader/lib/index' {
  declare module.exports: any;
}

declare module 'responsive-loader/sharp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'responsive-loader/jimp.js' {
  declare module.exports: $Exports<'responsive-loader/jimp'>;
}
declare module 'responsive-loader/lib/adapters/jimp.js' {
  declare module.exports: $Exports<'responsive-loader/lib/adapters/jimp'>;
}
declare module 'responsive-loader/lib/adapters/sharp.js' {
  declare module.exports: $Exports<'responsive-loader/lib/adapters/sharp'>;
}
declare module 'responsive-loader/lib/index.js' {
  declare module.exports: $Exports<'responsive-loader/lib/index'>;
}
declare module 'responsive-loader/sharp.js' {
  declare module.exports: $Exports<'responsive-loader/sharp'>;
}
