// flow-typed signature: cf8c9ba7a56c434796e74c56cda1b86f
// flow-typed version: <<STUB>>/styled-bootstrap-grid_v3.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-bootstrap-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-bootstrap-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-bootstrap-grid/dist/aliases/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/aliases/makeAliases' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/aliases/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/BaseCSS/BaseCSS' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/BaseCSS/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/BaseCSS/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Col/Col' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Col/css' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Col/getDataName' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Col/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Col/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Container/Container' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Container/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Container/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Row/css' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Row/getDataName' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Row/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Row/Row' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/Row/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/ThemeProvider' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/media/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/media/media' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/media/types' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/utils/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/utils/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-bootstrap-grid/dist/aliases/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/aliases/index'>;
}
declare module 'styled-bootstrap-grid/dist/aliases/makeAliases.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/aliases/makeAliases'>;
}
declare module 'styled-bootstrap-grid/dist/aliases/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/aliases/types'>;
}
declare module 'styled-bootstrap-grid/dist/components/BaseCSS/BaseCSS.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/BaseCSS/BaseCSS'>;
}
declare module 'styled-bootstrap-grid/dist/components/BaseCSS/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/BaseCSS/index'>;
}
declare module 'styled-bootstrap-grid/dist/components/BaseCSS/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/BaseCSS/types'>;
}
declare module 'styled-bootstrap-grid/dist/components/Col/Col.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Col/Col'>;
}
declare module 'styled-bootstrap-grid/dist/components/Col/css.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Col/css'>;
}
declare module 'styled-bootstrap-grid/dist/components/Col/getDataName.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Col/getDataName'>;
}
declare module 'styled-bootstrap-grid/dist/components/Col/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Col/index'>;
}
declare module 'styled-bootstrap-grid/dist/components/Col/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Col/types'>;
}
declare module 'styled-bootstrap-grid/dist/components/Container/Container.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Container/Container'>;
}
declare module 'styled-bootstrap-grid/dist/components/Container/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Container/index'>;
}
declare module 'styled-bootstrap-grid/dist/components/Container/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Container/types'>;
}
declare module 'styled-bootstrap-grid/dist/components/Row/css.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Row/css'>;
}
declare module 'styled-bootstrap-grid/dist/components/Row/getDataName.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Row/getDataName'>;
}
declare module 'styled-bootstrap-grid/dist/components/Row/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Row/index'>;
}
declare module 'styled-bootstrap-grid/dist/components/Row/Row.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Row/Row'>;
}
declare module 'styled-bootstrap-grid/dist/components/Row/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/Row/types'>;
}
declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/ThemeProvider/index'>;
}
declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/ThemeProvider.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/ThemeProvider/ThemeProvider'>;
}
declare module 'styled-bootstrap-grid/dist/components/ThemeProvider/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/components/ThemeProvider/types'>;
}
declare module 'styled-bootstrap-grid/dist/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/index'>;
}
declare module 'styled-bootstrap-grid/dist/media/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/media/index'>;
}
declare module 'styled-bootstrap-grid/dist/media/media.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/media/media'>;
}
declare module 'styled-bootstrap-grid/dist/media/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/media/types'>;
}
declare module 'styled-bootstrap-grid/dist/utils/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/utils/index'>;
}
declare module 'styled-bootstrap-grid/dist/utils/types.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/utils/types'>;
}
