// flow-typed signature: 8bde70e2ed80de9c8b201e56d7c56c2a
// flow-typed version: <<STUB>>/switchcase_v^1.0.11/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'switchcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'switchcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'switchcase/browser/switchcase' {
  declare module.exports: any;
}

declare module 'switchcase/browser/switchcase.min' {
  declare module.exports: any;
}

declare module 'switchcase/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'switchcase/browser/switchcase.js' {
  declare module.exports: $Exports<'switchcase/browser/switchcase'>;
}
declare module 'switchcase/browser/switchcase.min.js' {
  declare module.exports: $Exports<'switchcase/browser/switchcase.min'>;
}
declare module 'switchcase/index' {
  declare module.exports: $Exports<'switchcase'>;
}
declare module 'switchcase/index.js' {
  declare module.exports: $Exports<'switchcase'>;
}
declare module 'switchcase/test/index.js' {
  declare module.exports: $Exports<'switchcase/test/index'>;
}
