export const REGISTER_APP = 'REGISTER_APP';

export const REGISTER_SHOWCASES = 'REGISTER_SHOWCASES';

export const UPDATE_SHOWCASE = 'UPDATE_SHOWCASE';
export const EMPTY_SHOWCASE = 'EMPTY_SHOWCASE';

export const UPDATE_LIGHT_BOX_IMAGES = 'UPDATE_LIGHT_BOX_IMAGES';
export const EMPTY_LIGHT_BOX_IMAGES = 'EMPTY_LIGHT_BOX_IMAGES';
